### ISSUE TITLE
preventing vpn dialog box confirmation to appear

### ISSUE THREAD

**Issue by cubakcabak** [AndroidFire/DroidTint#1]
just like the title said.

if i activating droidtint, any vpn apps cant be used, because the vpn confirmation dialog box wont appear.

used it on android 4.4.2

i dont have device with another version to try on.

**Comment by SalimMahdAlmas** [comment]
thanks for reporting would you give me a screenshot

**Comment by SalimMahdAlmas** [comment]
put the app into blacklist this may work

**Comment by cubakcabak** [comment]
i have tried to put the app into blacklist, but the error still ocurred.

the screenshot wont tell much, as it just showing vpn app main interface with nothing else to show.

you might reproduce it by trying any of the vpn apps on the playstore.

my use vpn app is opermax, betternet and neopard.
